spring.application.name=custom-dress

spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://ankitgurjar0607:Admin%40123@cluster0.6qrtx3y.mongodb.net/dress?retryWrites=true&w=majority}

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:dilhyskup}
cloudinary.api_key=${CLOUDINARY_API_KEY:928437565592255}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:oAHMpZHJaWyTbVpT0E_ojCv_M1g}

jwt.secret=${JWT_SECRET:yourSecretKeyYourSecretKeyYourSecretKey123}

